# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs: 
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      inputs:
        containerRegistry: 'docker hub'
        repository: 'devopscontinens'
        command: 'build'
        Dockerfile: '**/Dockerfile'
    - task: CmdLine@2
      displayName: Docker image list after build
      inputs:
        script: 'docker images ls'
# - stage: Scan
#   displayName: Scan Image
#   jobs:
#   - job: Scan
#     steps:

    - task: Docker@2
      inputs:
        containerRegistry: 'aqua registry'
        command: 'login'
    - task: CmdLine@2
      displayName: Docker image list after login
      inputs:
        script: 'docker image ls'
    - task: aquasecScanner@4
      inputs:
        image: 'nginx:latest'
        scanType: 'local'
        register: true
        hideBase: false
        showNegligible: false
        windowsScannerVersion: '4.2.0'
        registry: 'local'
        connection: 'aqua-csp'
        caCertificates: true
        scanMalware: true
        showWillNotFix: true